### ISSUE TITLE
Use rst for the readme instead of markdown

### ISSUE THREAD

**Issue by hugorodgerbrown** [basecrm/basecrm-python#1]
PyPI doesn't like markdown, and the `pypandoc` conversion in the setup hasn't worked, or was run by someone without pypandoc installed - as it's come over as markdown on the official release page - https://pypi.python.org/pypi/basecrm/1.0.3

![screenshot 2015-05-05 23 53 39](https://cloud.githubusercontent.com/assets/200944/7484618/897e75c6-f382-11e4-8f62-591a30ae693b.png)

**Comment by hugorodgerbrown** [comment]
Have submitted PR for this.

**Comment by iaintshine** [comment]
Hi Hugo,

You're right. To prevent the issue with `pypandoc` in future, we'll move to reStructuredText.   

Thanks for you input.

**Comment by iaintshine** [comment]
Merged
