### ISSUE TITLE
Exception raised when rate limit is exceeded!

### ISSUE THREAD

**Issue by Zaab1t** [basecrm/basecrm-python#18]
Exception: Unknown HTTP error response. Json expected. HTTP response code=429. HTTP response body=

This is line 158 in http_client.py. It never reaches 165, because your HTTP response code 429 is invalid json.

**Comment by Zaab1t** [comment]
While this can be "fixed" in this module, it happens because your 429 response has no body and therefore resp.json() throws  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0).

This happens when you do json.dumps('').

I also sent an email as that might be a better way to reach you.

**Comment by piotr-szczesniak** [comment]
Solved in 35aec00d7db342a4e5d23f1893fc1a8c6c2fb8ea
