### ISSUE TITLE
only 25 items

### ISSUE THREAD

**Issue by konradbjk** [basecrm/basecrm-python#27]
Hello, 

Whatever I call I receive only 25 first items it is totally not usable SDK.

**Comment by acanpacan** [comment]
Hey @konradbjk ,

the API is paginated, you can read more about Pagination in our [Requests documentation](https://developers.getbase.com/docs/rest/articles/requests)

In the client, you can pass the `page` param just like any other param:
```
client.deals.list() # first page by default
client.deals.list(page=2) # to get the next page
```
We will add a section regarding pagination to README.
