### ISSUE TITLE
`pip install basecrm` is broken

### ISSUE THREAD

**Issue by zsiciarz** [basecrm/basecrm-python#3]
After switching the readme from markdown to RST, the package can't be installed from PyPI. 

```sh
$ pip install basecrm
Collecting basecrm
  Using cached basecrm-1.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-FXRjSP/basecrm/setup.py", line 28, in <module>
        long_description=long_description(),
      File "/tmp/pip-build-FXRjSP/basecrm/setup.py", line 17, in long_description
        content = read_file('README.md')
      File "/tmp/pip-build-FXRjSP/basecrm/setup.py", line 8, in read_file
        f = open(name)
    IOError: [Errno 2] No such file or directory: 'README.md'
```

Perhaps a new release would fix that? By the way if setup.py reads `README.rst`, it should be listed in the [MANIFEST.in](https://packaging.python.org/en/latest/distributing.html#manifest-in) file.

**Comment by zsiciarz** [comment]
Note: the temporary workaround is to install from a commit tarball: 
`pip install https://github.com/basecrm/basecrm-python/archive/f0882f4384743621f5e5fe7c53b044f7a5a0f819.zip#egg=basecrm`

**Comment by iaintshine** [comment]
Hi,

We plan to release a new version in a day or two and definitely fix the
issue.

Thanks for your help.

On Mon, Jun 1, 2015 at 11:52 AM, Zbigniew Siciarz <notifications@github.com>
wrote:

> Note: the temporary workaround is to install from a commit tarball:
> pip install
> https://github.com/basecrm/basecrm-python/archive/f0882f4384743621f5e5fe7c53b044f7a5a0f819.zip#egg=basecrm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/basecrm/basecrm-python/issues/3#issuecomment-107384221>
> .
>



-- 
http://about.me/iaintshine
