### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Client'

### ISSUE THREAD

**Issue by vascopedro** [basecrm/basecrm-python#4]
import basecrm
client = basecrm.Client(access_token='[ACCESS_TOKEN]')
AttributeError                            Traceback (most recent call last)
<ipython-input-8-db9a07e41db4> in <module>()
----> 1 client = basecrm.Client(access_token='[ACCESS_TOKEN]')

AttributeError: 'module' object has no attribute 'Client'

I have tried in multiple ways, but I keep getting this basic error

**Comment by hugorodgerbrown** [comment]
@vascopedro did you close this issue because it's fixed, or not an issue (just need to know whether it needs a patch)?
