### ISSUE TITLE
source_id missing from keys to persist for LeadsService

### ISSUE THREAD

**Issue by kingfink** [basecrm/basecrm-python#5]
Hello - I noticed that source_id is missing from the keys to persist for the LeadsService (line 376 of basecrm/serivces.py). Can you please add this?

Thanks!

**Comment by hugorodgerbrown** [comment]
Hi @kingfink, since you've already done the hard work, feel free to fork and fix.

We'll fix in due course, but I'm afraid can't guarantee when this may be.

**Comment by kingfink** [comment]
OK great, it was a very straightforward change. I've done as you asked for
my personal use, and even sent a PR to try and make it easy on your end.
Thanks!

On Wed, Jan 27, 2016 at 5:08 AM, Hugo Rodger-Brown <notifications@github.com
> wrote:

> Hi @kingfink <https://github.com/kingfink>, since you've already done the
> hard work, feel free to fork and fix.
>
> We'll fix in due course, but I'm afraid can't guarantee when this may be.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/basecrm/basecrm-python/issues/5#issuecomment-175525392>
> .
>



-- 
Tim Finkel
tim.finkel@gmail.com
518.573.5942

**Comment by iaintshine** [comment]
@kingfink many thanks for your help. I've merged the PR. Will release it with the next minor version update.
